version: '3.0'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:latest
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    ports:
      - '8080:8080'

  frontend:
    image: nginx:1.26-alpine
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - graphql-engine
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'

  minio:
    image: minio/minio:latest
    container_name: myapp_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  pg_data:
  minio-data:
